# Generated by Django 4.0.3 on 2022-03-15 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.classroom'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='school.department'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradeevaluation',
            name='course_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_evaluations', to='school.courseclass'),
        ),
        migrations.AddField(
            model_name='gradeevaluation',
            name='evaluation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_evaluations', to='school.evaluation'),
        ),
        migrations.AddField(
            model_name='gradeevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_evaluations', to='school.student'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='course_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='school.courseclass'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='school.professor'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='type_evaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='school.typeevaluation'),
        ),
        migrations.AddField(
            model_name='department',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='school.building'),
        ),
        migrations.AddField(
            model_name='department',
            name='coordinator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator', to='school.professor'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='school.course'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='professor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_classes', to='school.professor'),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_class', to='school.schedule'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='school.course'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='school.building'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('classroom', 'start_class')},
        ),
        migrations.AlterUniqueTogether(
            name='gradeevaluation',
            unique_together={('course_class', 'student', 'evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('course_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('building', 'number')},
        ),
    ]
