# Generated by Django 4.0.3 on 2022-03-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_professor_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='creditos',
        ),
    ]
