# Generated by Django 4.0.3 on 2022-03-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='school.course'),
        ),
    ]
