# Generated by Django 4.0.3 on 2022-03-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_departamento_creditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='registro',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
