# Generated by Django 4.0.3 on 2022-03-16 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_professor_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='coordenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='school.professor'),
        ),
    ]
