# Generated by Django 4.0.3 on 2022-03-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_course_prerequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='school.course'),
        ),
    ]
