# Generated by Django 4.0.3 on 2022-03-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_rename_periodo_semestre_alter_semestre_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('porta', 'predio')},
        ),
    ]
