# Generated by Django 4.0.3 on 2022-03-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_schedule_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclass',
            options={'verbose_name': 'Course Class', 'verbose_name_plural': 'Course Classes'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.AddField(
            model_name='test',
            name='course_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='school.courseclass'),
        ),
    ]
