# Generated by Django 4.0.3 on 2022-03-14 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_courseclass_options_remove_test_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('course_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_tests', to='school.courseclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_tests', to='school.student')),
            ],
            options={
                'verbose_name': 'Grade Test',
                'verbose_name_plural': 'Grade Tests',
            },
        ),
        migrations.RemoveField(
            model_name='test',
            name='grade_value',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.AddField(
            model_name='gradetest',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_tests', to='school.test'),
        ),
        migrations.AlterUniqueTogether(
            name='gradetest',
            unique_together={('course_class', 'student', 'test')},
        ),
    ]
