# Generated by Django 4.0.3 on 2022-03-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_sala_capacidade_sala_tem_projetor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('inicio', 'sala')},
        ),
    ]
