# Generated by Django 4.0.3 on 2022-03-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
