# Generated by Django 4.0.3 on 2022-03-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_curso_codigo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('ano', 'semestre', 'horario')},
        ),
    ]
