# Generated by Django 4.0.3 on 2022-03-16 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_alter_disciplina_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='professor',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='school.curso'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='school.professor'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='school.semestre'),
        ),
    ]
