# Generated by Django 4.0.3 on 2022-03-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_curso_professor_alter_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alunos', to='school.disciplina'),
        ),
    ]
